### PR TITLE
WIP: major refactor

### PR DESCRIPTION
**Pull request by betodealmeida**

### CODE REVIEW

**Comment by vjousse** [comment]
Hello,
I was planning to use nefelibata but then I came across this PR. I am now wondering if I can go with the `main` branch or if I should use this one?
Thanks!

**Comment by betodealmeida** [comment]
> Hello, I was planning to use nefelibata but then I came across this PR. I am now wondering if I can go with the `main` branch or if I should use this one? Thanks!

Hi, @vjousse!

This branch has been stable for a few months, now, and it's what I've been using to blog on https://blog.taoetc.org/ and gemini://taoetc.org/. The main differences in this new refactor are:

## Improvements

- You can generate a [Gemini capsule](https://gemini.circumlunar.space/) from the Markdown posts.
- You can announce posts to a few Gemini aggregators.
- You can have multiple announcers of the same type (eg, announce on two different Mastodon instances).
- You can group tags into categories now.
- Performance has improved a lot, and all the operations run in parallel and only if needed.

## Still missing

- Some announcers are still missing: Twitter, WT.Social, Medium.
- No Twitter card as well.
- No warnings if the generated HTML (or Gemtext) has links to external resources.
- No NeoCities publisher.

If you're interested in giving it a try I can update the docs today, let me know!

**Comment by vjousse** [comment]
Hi,
I am definitively interested, especially the gemini part. I would be happy to contribute if needed too.
Thanks for your work :)

**Comment by betodealmeida** [comment]
> Hi, I am definitively interested, especially the gemini part. I would be happy to contribute if needed too. Thanks for your work :)

Awesome, let me merge the branch into `main` and update the docs. I'll do that right now.

**Comment by betodealmeida** [comment]
Merged in https://github.com/betodealmeida/nefelibata/pull/22

**Comment by betodealmeida** [comment]
@vjousse I merged the `refactor` branch into `main`, and update the `README`. In the next few days I'm going to work on user and developer documentation, and add some tickets for the roadmap, if you're interested in helping. Let me know if you have any questions!

**Comment by vjousse** [comment]
Awesome! Giving it a try right now :)

**Pull request closed without merging**
